site_name: SGLang RAG Demo
site_description: RAG implementation with SGLang structured prompts
site_url: https://example.com/sglang-rag-demo

repo_name: your-username/sglang-rag-demo
repo_url: https://github.com/your-username/sglang-rag-demo

docs_dir: src
site_dir: ../site

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Architecture:
    - System Overview: architecture/overview.md
    - Vector Store: architecture/vector-store.md
    - LLM Integration: architecture/llm-integration.md
  - Guides:
    - Prompt Design: guides/prompt-design.md
    - Performance Tuning: guides/performance.md
    - Deployment: guides/deployment.md
  - API Reference:
    - RAG System: api/rag-system.md
    - Vector Store: api/vector-store.md
    - Document Processor: api/document-processor.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
